version: '3'
services:
  deployment:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: .
      dockerfile: Dockerfile.development
    ports:
      - '4500:3000'
    volumes:
      - .:/app
      - /app/node_modules
    
